name: graphworld
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - graph-tool
  - pip
  - cython
  - networkit
  - "numpy>=1.21,<1.24"
  - "scipy>=1.7.0,<1.10.0"
  - absl-py
  - gcsfs
  - gin-config
  - fsspec
  - networkx
  - notebook
  - matplotlib
  - pycairo
  - seaborn
  - ujson
  - scikit-learn
  - hyperopt